#!/bin/sh

if ! [ -f "$HOME/.zshrc-local" ]; then
  echo "Creating local zsh config file"
  touch "$HOME/.zshrc-local"
fi

if ! command -v antigen >/dev/null 2>&1; then
  echo "Installing antigen"
  curl -L git.io/antigen > ~/.antigen.zsh
fi

system_type=$(uname -s)

if [ "$system_type" = "Darwin" ]; then
  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing homebrew"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    eval "$(/opt/homebrew/bin/brew shellenv)"
  fi

  if [ -f "$HOME/.Brewfile" ]; then
    echo "Updating homebrew bundle"
    brew bundle --global
  fi

  echo "Setting iTerm2 to load preferences from home folder"
  defaults write com.googlecode.iterm2 LoadPrefsFromCustomFolder -bool true
  defaults write com.googlecode.iterm2 PrefsCustomFolder -string "~"

  echo "Hiding desktop"
  defaults write com.apple.finder CreateDesktop -bool false && killall Finder

  echo "Keyboard settings"
  defaults write -g ApplePressAndHoldEnabled -bool false
  defaults write -g KeyRepeat -int 1
  defaults write -g InitialKeyRepeat -int 10
  echo "⚠️ Map caps lock to escape key"

  echo "Dragy windows"
  defaults write -g NSWindowShouldDragOnGesture -bool true

  # set dozer, scroll reverser, sensible-sidebuttons as login items
  # also is sensible-sidebuttons still needed?
fi
